language: objective-c
osx_image: xcode611

before_install:
    - export LANG=en_US.UTF-8
    - env
    - locale
    - pod --version
    - brew update
    - brew outdated xctool || brew upgrade xctool


script:
    - cd ios/Library
    - pod install
    - ./run-tests.sh
    - cd ../..
